version: '3.7'

services:
  osmosis:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/wslerry/osmosis:latest
    command: -a map
    environment:
      # - OSMOSIS_VERSION=0.49.2
      - JAVACMD_OPTIONS=-Xmx4g -Xms2g  # Example: 1.5 GB pbf size, -> 1.5*2*2=6. Xmx AT LEAST `-Xmx6g`
      - OSM_SEA_FILE=sea.osm # create a sea layer 
      - OSM_PBF_FILE=malaysia-singapore-brunei-latest.osm.pbf # get your data from geofabrik.de
    volumes:
      - ./osm/data:/data/input/
      - ./output:/data/output/
      # - ./scripts:/opt/osm
      # - ./plugins:/opt/osm/plugins
    # entrypoint: "./entrypoint.sh"
    restart: unless-stopped